新增命令执行，yaml文件处理
FeixiDev/DALAvailability pull request #1
Opened 2022-09-22 09:47 UTC by shikifyj

2022-09-23 05:26 UTC, mattie-feng requested changes
问题：方法的实现与预期不符
另外，同时对各模块的方法添加注释说明

2022-09-23 05:26 UTC, mattie-feng commented on config_file.py
> +            yaml.dump(self.config, f, default_flow_style=False)
1. 跟预期不符
2. 请说明当前该函数的作用

2022-09-23 05:26 UTC, mattie-feng commented on exec_command.py
> +                return err
跟预期返回值不符，需要获得的是字典类型的数据，包含该命令是否执行成功的这一个信息

2022-09-23 05:26 UTC, mattie-feng commented on exec_command.py
> +            return False
与预期返回值不符

2022-09-23 05:26 UTC, mattie-feng commented on exec_command.py
> +            return False
与预期返回值不符

2022-09-23 05:26 UTC, mattie-feng commented on config_file.py
> +        with open(self.yaml_file, 'w', encoding='utf-8') as f:
添加异常处理

2022-09-26 08:07 UTC, mattie-feng commented on log.py
> +
移出 log 类

2022-09-26 08:09 UTC, mattie-feng commented on log.py
> +            level = logging.debug
只有这个 debug 是小写吗
INFO、WARNING 都是全大写

2022-09-26 08:09 UTC, mattie-feng commented on log.py
> +        formatter = logging.Formatter(f"%(asctime)s - %(levelname)s -{self.ip}-{data1}-{data2}")
格式，注意空格

2022-09-26 08:12 UTC, mattie-feng commented on send_email.py
> +                 message2 = '“Sorry, there was a error with the test and the test exited”'):
为什么要加 `“ ”`？

2022-09-26 08:13 UTC, mattie-feng commented on send_email.py
> +            smtpObj = smtplib.SMTP()
为什么大写驼峰

2022-09-27 06:03 UTC, shikifyj commented on log.py
> +            level = logging.debug
debug应该大写

2022-09-27 06:31 UTC, shikifyj commented on exec_command.py
> +        self.SSHConnection = None
参考了VersaSDSToolset/VersaSDSInit/utils.py中该部分的写法

2022-09-27 06:35 UTC, shikifyj commented on send_email.py
> +                 message2 = '“Sorry, there was a error with the test and the test exited”'):
想的是在邮件中呈现的是“Congratulations, the test passes”  。也没啥意义，可以去掉

2022-09-30 01:40 UTC, mattie-feng requested changes

2022-09-30 01:40 UTC, mattie-feng commented on log.py
> +        formatter = logging.Formatter(f"%(asctime)s-%(levelname)s-{self.ip}-{data1}-{data2}")
- 之间加空格

2022-09-30 01:40 UTC, mattie-feng commented on send_email.py
> +        smtpObj = self.connect_stmp()
smtpObj 命名

2022-09-30 01:40 UTC, mattie-feng commented on send_email.py
> +        self.mail_pass = 'Githubhost1234'
优化：这部分邮件信息不写在代码中，后续通过配置文件填写发件人信息

2022-09-30 01:40 UTC, mattie-feng commented on exec_command.py
> +        self.SSHConnection = None
改成变量名的命名方式

2022-09-30 04:02 UTC, merged