优化测试相关代码
FeixiDev/DALAvailability pull request #12
Opened 2022-10-28 11:08 UTC by shikifyj

Single Primary，Automatic promotion和Trim/Discard support

2022-10-31 15:30 UTC, shikifyj commented
linstor_eviction,linstor命令响应测试，torget01

2022-11-02 09:37 UTC, mattie-feng requested changes
命令执行完都没有确认命令是否成功，其他问题详看下面 Comment，很多是整个程序中存在的问题，需要自己检查一遍

2022-11-02 09:37 UTC, mattie-feng commented on controller/autopromotion_tset.py
> +    def diskful_mount(self, drbd_route):
不符合预期的话不提示以及退出吗

2022-11-02 09:37 UTC, mattie-feng commented on controller/autopromotion_tset.py
> +        self.disk_cmd.mount_disk(drbd_route, self.controller_node)
检查是否执行成功了没？

2022-11-02 09:37 UTC, mattie-feng commented on controller/autopromotion_tset.py
> +        self.rw_cmd.dd_write(device_name, self.controller_node)
是否是 dd 操作执行完只会才会执行下一步操作，这样与预期不符

2022-11-02 09:37 UTC, mattie-feng commented on controller/__init__.py
> +from .singleprimary_tset import SinglePrimary
tset?  => test

2022-11-02 09:37 UTC, mattie-feng commented on controller/discard_tset.py
> +            print('Tset,passed')
检查你的单词

2022-11-02 09:37 UTC, mattie-feng commented on controller/discard_tset.py
> +        DiscardSupport().discard_support()
方法之前要有间隔
是否要都用 main 这个名字？建议改掉

2022-11-02 09:37 UTC, mattie-feng commented on controller/linstor_eviction.py
> +        self.sp_cmd = 'linstor controller sp DrbdOptions/AutoEvictAllowEviction false'
为什么写在这里？？？
recover_cmd 命令写错了

2022-11-04 02:53 UTC, closed without merging